create table users
(
    id       bigint generated by default as identity
        constraint users_pkey
            primary key,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    role     varchar(255)
);

alter table users
    owner to cdnooowshipnoa;

INSERT INTO public.users (email, name, password, role) VALUES ('admin@admin.com', 'Admin', '$2a$10$jJ.ACAMFs4vThaKVfOp.sOvZ3bmR0sV/YM6NATeHE1LRXVCb6cRGe', 'ROLE_ADMIN');
INSERT INTO public.users (email, name, password, role) VALUES ('user@user.com', 'User', '$2a$10$j80WIeYPEt4xZ4Vpb/I44OEettdHv7RtwES.tc0E4/n0CGkd8daou', 'ROLE_USER');
INSERT INTO public.users (email, name, password, role) VALUES ('paw1a@yandex.ru', 'Павел', '$2a$10$vMhG0zPlwhvKuLxbfnxrn.ypyl4KR/e5QqNYUWglbOmzv0zadw9E.', 'ROLE_ADMIN');
INSERT INTO public.users (email, name, password, role) VALUES ('foxleren.commercial@gmail.com', 'Foxleren', '$2a$10$pKl9QswmTUiJ9xEZQTMu0uN4dBQ2QOT.Hq9.Y/IWVfgxZd6lhY/pS', 'ROLE_ADMIN');